controllers:
    resource: ../src/Controller/
    type: attribute


api_graphql_entrypoint:
    path: /api/graphql
    controller: api_platform.graphql.action.entrypoint

graphiql:
    path: /docs/graphiql
    controller: api_platform.graphql.action.graphiql
    

# api_login_check:
#     path: /api/login
#     methods: ['POST']

api_login:
    path: /api/login
    methods: ['POST']



app_logout:
    path: /logout
    methods: GET